name: CD Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v1
        with:
          go-version: '1.16.2'
      - name: Build Binaries
        run: make versioned-binaries
      - name: Uploading Binaries
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.FLOW_TEST_SA }}
          path: ./cmd/flow/
          glob: 'flow-*'
          destination: flow-cli-test/
