name: CD Release

on:
  release:
    types: [published]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.16.2'
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v1
        with:
          go-version: '1.16.2'
      - name: Build Binaries
        run: make versioned-binaries
      - name: Uploading Binaries
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.FLOW_HOSTING_PROD_SA }}
          path: ./cmd/flow/
          glob: 'flow-*'
          destination: flow-cli/
          parent: false
      - name: Update Version
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.FLOW_HOSTING_PROD_SA }}
          path: ./
          glob: 'version.txt'
          destination: flow-cli/
  homebrew:
      name: Bump Homebrew formula
      runs-on: ubuntu-latest
      steps:
        - uses: mislav/bump-homebrew-formula-action@v1
          with:
            formula-name: flow-cli
          env:
            COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
